In [1]:
import numpy as np

In [3]:
nt = np.load('data/nt_test.npy')

In [5]:
nt_labels = np.load('data/nt_test_labels.npy')

In [6]:
nt_tc_labels = np.load('data/nt_test_tc_labels.npy')

In [8]:
nt_labels[:10]

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [10]:
# tumor
np.sum(nt_labels[:, 1] == 1)

144

In [11]:
nt_tumor = nt[nt_labels[:, 1] == 1]

In [12]:
nt_tumor.shape

(144, 60483, 1)

In [13]:
nt_tc_probs = nt_tc_labels

In [21]:
nt_tc_labels = np.argmax(nt_tc_probs, axis=1)

In [22]:
nt_tc_labels.shape

(280,)

In [16]:
from keras.utils import np_utils

In [23]:
nt_tc_labels = np_utils.to_categorical(nt_tc_labels, 36)

In [27]:
np.save('data/nt_test_tc_labels', nt_tc_labels)
# np.save(DATA_DIR + 'nt_test_tc_labels', nt_test_tc_labels)

In [28]:
nt_tc_probs = np.load('data/nt_train_tc_labels.npy')
nt_tc_labels = np.argmax(nt_tc_probs, axis=1)
nt_tc_labels = np_utils.to_categorical(nt_tc_labels, 36)
np.save('data/nt_train_tc_labels', nt_tc_labels)

In [30]:
nt_train_tc = np.load('data/nt_train_tc_labels.npy')

In [31]:
nt_train_tc[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [32]:
tc_labs = np.load('data/tc_train_labels.npy')

In [33]:
tc_labs[:2]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)